### ISSUE TITLE
Type error with Puppet v4 parser

### ISSUE THREAD

**Issue by riton** [jhoblitt/puppet-udev#20] opened 2016-08-03 11:39 UTC
With the latest version of puppetserver, we encounter the following error:

```
Evaluation Error: Error while evaluating a Function Call, 
Module udev is not supported on RedHat release 7 at /etc/puppetlabs/code/environments/production/modules/udev/manifests/params.pp:42:13
```

We've tested that the error fades away if we _cast_ operatingsystemmajrelease to either _string_ or _integer_.

**Comment by jhoblitt** [comment] 2017-02-02 15:44
@riton / @nexecook I've added a beaker acceptance tests on centos 7 to the travis matrix that is passing.  Is this error still reproducible?  Odd that the problem would be puppetserver specific.

**Comment by nexecook** [comment] 2017-02-02 18:47
I can't reproduce it anymore.

**Comment by jhoblitt** [comment] 2017-02-02 19:11
OK -- it may have been a puppetserver and/or facter version specific thing.  I'm going to close this ticket but if anyone can reproduce this, please reopen the issue.

**Closed by jhoblitt** 2017-02-02 19:11 UTC
